CREATE DATABASE 615813_doingsdone_11
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 615813_doingsdone_11;

CREATE TABLE users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(140) NOT NULL,
   email VARCHAR(128) NOT NULL UNIQUE,
   password VARCHAR(80) NOT NULL
);

CREATE TABLE projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    user_id INT NOT NULL
);

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    project_id INT NOT NULL,
    date_task TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file VARCHAR(255),
    is_done BIT,
    user_id INT NOT NULL
);